### ISSUE TITLE
How can i see true prediction for my variable

### ISSUE THREAD

**Issue by Hyphen133** [salesforce/OmniXAI#1]
Neither in Predict nor in Query Instance can I see my true prediction. I can only see the one predicted by model.
Is there a way to add it or this is not yet supported?

![image](https://user-images.githubusercontent.com/24831993/175053005-90dd352b-5d24-484f-86db-8ecc7aba2324.png)

**Comment by yangwenzhuo08** [comment]
Hi, thanks for raising this question. In the "predict" figure, you can move your cursor over the blue bar, it will show the prediction value. We will update this visualization in the next minor release to make it more clear (currently it supports classification better than regression). If you find any other questions, we are happy to help.
