### ISSUE TITLE
Omnixai is not working with bert fine tunned multitext classification problem.

### ISSUE THREAD

**Issue by loni9164** [salesforce/OmniXAI#12]
HI, I am trying to run omnixai explainer over the bert fine tunned multitext classifier model to debug the model. It throwing an error. Could you please look into notebook **https://github.com/loni9164/Text-explainer-issues/blob/main/BERT_omnixai.ipynb** and help to me fix the issues?

**Comment by yangwenz** [comment]
Hi, you can try LIME and IG for this model (removing "shap" from "explainers=["lime","shap"]"). SHAP only supports "transformers.pipelines.text_classification.TextClassificationPipeline" currently. We can help if there are other issues.

**Comment by loni9164** [comment]
HI yangawenz,

I just tried with "lime" alone and i got below error,
![image](https://user-images.githubusercontent.com/101520804/180607692-57509d69-5d0d-4629-84ed-597e32f339cc.png)

**Comment by yangwenz** [comment]
The input of the preprocessing function should be an instance of Text defined in OmniXAI, which cannot be a list. You can simply create a Text object by checking this example: https://github.com/salesforce/OmniXAI/blob/main/tutorials/nlp_imdb.ipynb
