### ISSUE TITLE
Ipython plot error 

### ISSUE THREAD

**Issue by sami-ekimetrics** [salesforce/OmniXAI#18]
Hello, 
I am running OmniXAI on tabular data for a binary classification task. All the functions are working well except the Ipython plot ones, which all throws this same error (picture attached). I couldn't identify what this error corresponds to. Could you please help me fix this issue ? 

Thank you  

<img width="479" alt="erreur_omnixai" src="https://user-images.githubusercontent.com/110400907/182164224-862ae2e7-c535-4dab-bc6f-fe0e7a681052.png">

**Comment by yangwenz** [comment]
Does the dashboard work well in this case (as shown in the tutorial)? https://github.com/salesforce/OmniXAI/blob/main/tutorials/tabular_classification.ipynb

**Comment by yangwenz** [comment]
If this tutorial also has errors, could you please list your python, plotly dash, ipython version?

**Comment by yangwenz** [comment]
Besides ipython_plot, you can also try the following code:
fig = explanations_lime.plotly_plot(index=0, class_names=class_names)
fig.show()

**Comment by sami-ekimetrics** [comment]
Thank you for you answer ! 

When I try launching the dashboard as in the tutorial, I can't even access the site and the error raised is similar to the one in the following picture : 

![image](https://user-images.githubusercontent.com/110400907/182183090-6af66713-a30e-4b22-b4a1-94fbe9ccf081.png)

I tried the alternative code that you proposed and it doesn't work neither. The same error is thrown. 

Here are the version that I am working with : 

python : 3.9.5 (default, Nov 23 2021, 15:27:38) 
[GCC 9.3.0]

Ipython : '7.32.0'

plotlydash : 2.6.0

**Comment by yangwenz** [comment]
Another option is to call “plot” function instead of ipython plot and plotly plot, “plot” uses matplotlib to draw figures.
