### ISSUE TITLE
Why do the ALE plots show outliers that are not possible in my data?

### ISSUE THREAD

**Issue by xxkk1006** [salesforce/OmniXAI#36]
The maximum value of gap in my data is around 120, however, the ALE plot result has 467, what is the reason?
![image](https://user-images.githubusercontent.com/102650880/189019167-1235c98c-b822-4bcd-b34e-be31f65baf6e.png)

 In the PDP, the results is normal.
![image](https://user-images.githubusercontent.com/102650880/189019216-3bbd92d0-b312-4791-8867-6882fa22a3a7.png)

**Comment by yangwenz** [comment]
Hi, thanks for trying our library. For PDP, the bins for continuous valued features are created by 1st percentile to 99th percentile. For ALE, the bins are 0 to 100th percentile. So ALE has a larger range than PDP. We may add this range setup into the input parameters if necessary.
