### ISSUE TITLE
Which interpretable method can be used for 3D images?

### ISSUE THREAD

**Issue by xiaobaitubaibaibai** [salesforce/OmniXAI#42]
Dear author:
      I love your code very much, but I don't know which interpretable method works on 3D images,could you tell me if possible?

**Comment by yangwenz** [comment]
Hi, could you provide more background information about your application? For the current version, OmniXAI only supports image inputs with shape (batch_size, h, w, c). For a 3D images with another "depth" dimension, OmniXAI doesn't support it. But you may merge the depth map into the channel dimension if possible, and then all the explainers for vision models can be applied.

**Comment by xiaobaitubaibaibai** [comment]
> Hi, could you provide more background information about your application? For the current version, OmniXAI only supports image inputs with shape (batch_size, h, w, c). For a 3D images with another "depth" dimension, OmniXAI doesn't support it. But you may merge the depth map into the channel dimension if possible, and then all the explainers for vision models can be applied.
Thank you for the response，I would like to apply the interpretable method you provided to 3D pulmonary nodule CT image classification.Roughly understand what you said, thank you again for your reply

**Comment by yangwenz** [comment]
Thanks for trying OmniXAI. If you have other issues, feel free to contact us.
