### ISSUE TITLE
Gridded data

### ISSUE THREAD

**Issue by brdywltn** [salesforce/OmniXAI#43]
Hi, 

I've been using OmniXAI recently for investigative work purposes and am yet to crack the issue I'm having.

I work with a lot of meteorological data which is often in gridded format (3D).

My question is, does OmniXAI support 3D gridded data? 

Thanks

**Comment by yangwenz** [comment]
Hi, if the data can be converted into Tabular or Image, it is possible to apply OmniXAI. For example, the input data is tabular and the preprocessing function converts this tabular data into gridded format, and then the gridded format data is consumed by the model.
