### ISSUE TITLE
Not able to run the explainers with omnixai

### ISSUE THREAD

**Issue by keyansaravanan** [salesforce/OmniXAI#5]
attaching the screenshots, Please give me the resolution
![image](https://user-images.githubusercontent.com/70126510/178417980-23396aa4-9c88-4a5c-b3de-455d4f32ea45.png)
![image](https://user-images.githubusercontent.com/70126510/178418015-c20fcd54-2d18-416a-a5c0-57b42525b46f.png)

**Comment by yangwenzhuo08** [comment]
Hi, could you share which example you are running? It some modifications made based on the tutorial examples, could you highlight which part you changed? Thanks!

**Comment by yangwenzhuo08** [comment]
If you are working on classification problems, you can test this tabular example first:
https://github.com/salesforce/OmniXAI/blob/main/omnixai/tests/visualization/dashboard_tabular.py

**Comment by keyansaravanan** [comment]
![image](https://user-images.githubusercontent.com/70126510/178480633-28712ded-6736-438a-9109-a8a2bdc44a22.png)
This is the tutorial file I've ranned, but not working for every tutorial files I've ranned, getting the above error.

**Comment by yangwenz** [comment]
Which version of LIME is installed? And can you run this script succesfully?

**Comment by yangwenz** [comment]
Could you list the versions of python, LIME, OmniXAI? It will help us to reproduce the error. We recommend using Python >= 3.7.5 (will update the setup file in the next version).

**Comment by keyansaravanan** [comment]
Thanks I hope in python>=3.7.5, I was able to resolve this Issue, I do need testing experiments for all sort of datatypes which is missing in this Repo, If you would provide that too that would be great help for me.

**Comment by yangwenz** [comment]
All the examples can be found here: https://opensource.salesforce.com/OmniXAI/latest/tutorials.html#applications
You can also check the tutorials in the repo: https://github.com/salesforce/OmniXAI/tree/main/tutorials
It includes the examples for tabular, image, text and time-series data.

**Comment by yangwenz** [comment]
Thanks for raising the questions. Please do not hesitate to contact us if you find other issues or require new features that are missing in this library. We are happy to help.
