### ISSUE TITLE
A pair of two images as  input channel.

### ISSUE THREAD

**Issue by forevernoona** [salesforce/OmniXAI#51]
Dear Author;

Thanks for sharing the nice tool.

I would like to ask if this tool can receive a pair of two input images. I mean my model takes a pair of images in the input channel of the model. How can I extend your tools to take a pair of images?

Thanks in advance.

**Comment by yangwenz** [comment]
Hi, the gradient-based explainers for image assume that the model takes one image as its input. But you can implement a wrap over the model to handle two input images, e.g., the model takes two images as its inputs, while the wrap returns a new model that takes one image (you want to analyze) and treats the other image as a fixed variable. 

For example, suppose we have a pytorch model M that has a forward function "forward(x, y)". The wrap can be something like this:

class NewModel(nn.module):
    def __init__(m, y):
        self.model = m
        self.y = y

    def forward(x):
        return self.model(x, self.y)

This is just an example. You can implement the wrap according to your applications.
