### ISSUE TITLE
transformer.invert() does not perform as expected when inverting labels

### ISSUE THREAD

**Issue by ScottWilliamAnderson** [salesforce/OmniXAI#52]
Hi, wonderful tool you're building here!
I was following the tabular classification example, and seem to run in to an issue with the transformer inverting the labels:

using as reference https://github.com/salesforce/OmniXAI/blob/main/tutorials/tabular_classification.ipynb

After training the xgboost model, you can run transformer.invert(test), and it returns the original (train-split) dataset with 6513 rows.
But transformer.invert(test_labels) returns a Dataframe (?) with the first row populated with features, and the label as a column. 
Also, the length of this DF is 6405 rows (< 6513 rows of the test DF).

Apologies for the poor formatting, hopefully with this you can recreate the issue. 
Any ideas what may have caused this?
Thanks, Scott

**Comment by yangwenz** [comment]
Hi, "transformer.invert" cannot be used to invert "test_labels" directly. "test_labels" needs to be in the numpy array together with the features.

**Comment by ScottWilliamAnderson** [comment]
Thank you yangwenz! 
I would be inclined to suggest it could be useful to invert the labels directly (with the same or new function), given the unlabelled data can be inverted without issue. Alternatively, a small mention of this requirement could be mentioned in the docs.
That said, for anyone looking for a concise way to invert the labels (e.g. to get model's output on the test data), you can do it as follows

`transformer.invert(np.column_stack((test, test_labels))).to_pd()['label_column_name']`

Keep up the good work :)

**Comment by yangwenz** [comment]
Thanks so much for this suggestion. We will update it in the next minor version, e.g., invert labels if the input array has dim=1.
