### ISSUE TITLE
How does the pdp algorithm obtain the value range of the feature

### ISSUE THREAD

**Issue by SeibertronSS** [salesforce/OmniXAI#54]
How does the pdp algorithm obtain the value range of the feature

**Comment by yangwenz** [comment]
The value range is determined by the percentiles: "percentiles = np.linspace(0, 100, num=grid_resolution)".

**Comment by SeibertronSS** [comment]
> The value range is determined by the percentiles: "percentiles = np.linspace(0, 100, num=grid_resolution)". The original setting was "np.linspace(1, 99, num=grid_resolution)". We changed it to "np.linspace(0, 100, num=grid_resolution)" in the latest update.

Thanks for reply. I have another question, can OmniXAI customize the prediction function?

**Comment by SeibertronSS** [comment]
Thanks!

**Comment by SeibertronSS** [comment]
how about the output of the prediction function



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Yang ***@***.***> |
| Date | 12/14/2022 16:02 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [salesforce/OmniXAI] How does the pdp algorithm obtain the value range of the feature (Issue #54) |

The input of a prediction function should be Tabular, Image or Text defined in OmniXAI. They can be easily constructed from pandas dataframe, numpy array or pillow images.
