### ISSUE TITLE
GlobalShap method getting error.

### ISSUE THREAD

**Issue by adityakpathak** [salesforce/OmniXAI#56]
How can I use the global [shap](https://ibb.co/ZLkwRCR) method with my code?

**Comment by yangwenz** [comment]
For global shap, OmniXAI v1.2.3 needs to be installed. Here is an example: https://github.com/salesforce/OmniXAI/blob/main/omnixai/tests/explainers/shap/test_shap_tabular_global.py.

**Comment by adityakpathak** [comment]
@yangwenz Thank you it worked for me.
