### ISSUE TITLE
Missing features in LIME and SHAP

### ISSUE THREAD

**Issue by SeibertronSS** [salesforce/OmniXAI#59]
I followed the example to run the program of table classification, but I found that there are some features that are discarded in LIME and SHAP. I did not set ignored features. The original features of the data are  Age, Workclass, fnlwgt, Education, Education-Num, Marital, Status , Occupation, Relationship, Race , Sex, Capital Gain, Capital Loss, Hours per week, Country. The features in the LIME results are Capital Gain, Marital Status, Education-Num, Hours per week, Capital Loss, Age, Occupation, Sex, Race, Relationship. The features in the SHAP are Captial Gain, Age, Education Num, Marital Status, Occupation, Hours per week, Workclass, fnlwgt, Sex, Capital Loss, Education, Country, Relationship.

**Comment by SeibertronSS** [comment]
I'm not familiar with LIME and SHAP, is this because the algorithm itself discards some features?

**Comment by SeibertronSS** [comment]
I look at the source code and it seems that because of the feature selection.

**Comment by yangwenz** [comment]
No, it’s probably because some setups are wrong. Could you try the examples in the tutorial?

**Comment by yangwenz** [comment]
If the output doesn’t contain some features, you can consider their feature importance scores are zero.

**Comment by SeibertronSS** [comment]
> No, it’s probably because some setups are wrong. Could you try the examples in the tutorial?

The example I use is in the tutorial.

**Comment by SeibertronSS** [comment]
My lime package version is 0.2.0.1. I find a parameter called `feature_selection` in the class LimeTabularExplainer. The default value of the `feature_selection` is `auto`

**Comment by yangwenz** [comment]
If you want to set this parameter, you can set the kwargs for lime when initializing a tabular explainer as shown in the example.

**Comment by yangwenz** [comment]
E.g.,  "lime": {"kernel_width": 3, “feature_selection”: some value}

**Comment by SeibertronSS** [comment]
OK

**Comment by SeibertronSS** [comment]
Thanks!
