### ISSUE TITLE
Task Type

### ISSUE THREAD

**Issue by clh-b** [salesforce/OmniXAI#6]
Currently task type only support "classification" or "regression"?
Will detection be support soon?

**Comment by yangwenz** [comment]
For tabular and image data, OmniXAI only supports classification and regression or some tasks that can be converted as classification or regression. For time-series data, it supports forecasting and anomaly detection. We are working on more vision and NLP tasks, e.g., visual-language models. 

For detection you mention, is it object detection or anomaly detection?

**Comment by clh-b** [comment]
I refer to objection detection. 
Is anomaly detection supported since mentioned about it?

**Comment by yangwenz** [comment]
For object detection, you can implement a simple wrapper over the object detection model. The outputs of the wrapper can be the predicted class probabilities (view as a classification task) or the locations of the bounding box (view as a regression task), and then apply gradient-based explainers such as Grad-CAM for explanation.

For an anomaly detection problem, it is straightforward to consider it as a classification (if the detector is a binary classifier) or regression (if the detector outputs anomaly scores) problem.

**Comment by clh-b** [comment]
Thank you
