### ISSUE TITLE
The Kernel appears to have died

### ISSUE THREAD

**Issue by SouCh305** [salesforce/OmniXAI#64]
I have tried many times to implement OmniXAI Vision tutorial, but when i tried to import the _VisionExplainer library_ the message "**The kernel appears to have died**" appears before finishing the importation. Is there any solution to solve this problem please?

![kernel died](https://user-images.githubusercontent.com/111082366/210313647-61035fc6-8b5b-405c-900d-e87c37c936ed.png)

**Comment by yangwenz** [comment]
It seems a Jupyter notebook problem. Could you restart the notebook kernel?

**Comment by SouCh305** [comment]
I tried to restart it but it gives the same message.

**Comment by yangwenz** [comment]
The issue probably doesn't come from OmniXAI. Please check the environment installation, e.g., opening a python terminal and run those import commands to see if there are some errors.

**Comment by SouCh305** [comment]
Thank you for answering my question. The problem is in my Jupyter notebook.
