### ISSUE TITLE
AssertionError: Explainer lime -- training_data should be an instance of Tabular.

### ISSUE THREAD

**Issue by SouCh305** [salesforce/OmniXAI#65]
I'm trying to run [OmniXAI in ML Workflow tutorial](https://github.com/salesforce/OmniXAI/blob/main/tutorials/omnixai_in_ml_workflow.ipynb), in the cell:

`explainers = TabularExplainer(
    explainers=["lime", "shap", "mace", "pdp", "ale"],
    mode="classification",
    data=train_data,
    model=gbtree,
    preprocess=lambda z: transformer.transform(z),
    params={
        "lime": {"kernel_width": 3},
        "shap": {"nsamples": 100},
        "mace": {"ignored_features": ["Marital Status"]}
    }
)`

I got this error: 
> AssertionError: Explainer lime -- training_data should be an instance of Tabular.

How can I solve it?

**Comment by yangwenz** [comment]
Please make sure that train data is an instance of the Tabular class.

**Comment by SouCh305** [comment]
I solved it. Thank you.
