### ISSUE TITLE
What if analysis tool?

### ISSUE THREAD

**Issue by Giuseppe-Accardo** [salesforce/OmniXAI#66]
Hello everyone and congratulations on the work you have done!

I was wondering if it was possible to create a "What if Analysis"? i.e. when a user views graphs (e.g. Tabular) if the user can manually enter the values ​​of the featuers or change them!

Thank you!

**Comment by yangwenz** [comment]
Hi, thanks for trying OmniXAI. This is a good suggestion. Actually, we planned to add "what-if" analysis in the next release. The dashboard needs some updates.

**Comment by Giuseppe-Accardo** [comment]
Thanks for reply. I am happy that you have planned it for the next release! 

I asked because it would be an important feature to be aligned with the main competitors. Could you tell me when the next release will be planned? 

Thanks a lot!

**Comment by yangwenz** [comment]
Probably the new version can be release in Feb if we are not too busy on the other projects. It will include more figures and text descriptions for uses to understand the generated explanations better.
