### ISSUE TITLE
TimeseriesExplainer for forecasting?

### ISSUE THREAD

**Issue by wang99711123** [salesforce/OmniXAI#70]
Thanks for the excellent work!
And I wonder if OmniXAI supports interpretability of time series forecasting?

**Comment by yangwenz** [comment]
Yes, but the support of time series forecasting in the current version is limited. It only includes SHAP for time series forecasting, and the running time may be long if the model uses a long historical data for forecasting. We will improve this part in the future release.

**Comment by wang99711123** [comment]
I would like to know, how to use the interpretability of time series forecasting in the current version?
thank you!

**Comment by yangwenz** [comment]
It is "feature-attribution" explanation. For example, the forecasting model is x_t = f(x_{t-1}, x_{t-2}, ..., x_{t-k}). It will compute the feature attribution/importance scores of x_{t-1}, x_{t-2}, ..., x_{t-k} when the model predicts x_t. The lib also computes the feature importance scores for the timestamps besides the observed values x_{t-1}, x_{t-2}, ..., x_{t-k}.

**Comment by wang99711123** [comment]
OK I see, thanks a lot！
