### ISSUE TITLE
Question on the Image class

### ISSUE THREAD

**Issue by soumen-ghosh** [salesforce/OmniXAI#73]
Hi,

I've a question on the Image class (from omnixai.data.image). I'm working on the WM811K dataset. After some preprocessing, my images are 2-D array (128x128) with values between 0-1. 

```
import matplotlib.pyplot as plt
data1 = falsePositiveDF["WAFER_MAP"].iloc[0]
image = tf.expand_dims(input=data1, axis=2)
plt.axis("off")
plt.imshow(image, origin="lower", cmap="gray")
plt.show()
```

The above code produces something like this -
![image](https://user-images.githubusercontent.com/84480006/217391366-ea78a162-3e31-47cb-8134-fe3b0a40adba.png)

But when I convert it to the Image object to use GradCAM (from omnixai.explainers.vision.specific.gradcam), I see the image is distorted (the circular wafer is gone). What am I doing wrong? Do I need to scale the image pixels to 0-255?

```
import plotly.express as pltex
from omnixai.data.image import Image
from PIL import Image as PilImage
test_img1 = Image(PilImage.fromarray(obj=data1, mode="L"))
fig = pltex.imshow(test_img1.to_pil(), origin="lower", binary_string=True)
fig.show()
```
The above code produces something like this - 
![image](https://user-images.githubusercontent.com/84480006/217392179-791c41bc-cd65-4f7a-9d42-5af9a4798f85.png)

As a result, when I am trying to use the GradCAM, things are not working.

**Comment by yangwenz** [comment]
Hi, this seems a formatting issue. To create an "Image" object, you can scale the values to [0, 255] and take the numpy array as the input without creating a Pillow image.

**Comment by yangwenz** [comment]
Here is the reference: https://opensource.salesforce.com/OmniXAI/latest/omnixai.data.html#module-omnixai.data.image

**Comment by soumen-ghosh** [comment]
Thank you. I'll try it this week and update.
