### ISSUE TITLE
Does OmniXAI apply for a patent?

### ISSUE THREAD

**Issue by SeibertronSS** [salesforce/OmniXAI#75]
Does OmniXAI apply for a patent?

**Comment by yangwenz** [comment]
No, we don’t apply for a patent. We only applied a patent for the MACE algorithm.

**Comment by SeibertronSS** [comment]
Can I use MACE in business?



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Yang ***@***.***> |
| Date | 02/10/2023 08:06 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [salesforce/OmniXAI] Does OmniXAI apply for a patent? (Issue #75) |

No, we don’t apply for a patent. We only applied a patent for the MACE algorithm.

**Comment by yangwenz** [comment]
Yes, and please follow the license in this repo.

**Comment by SeibertronSS** [comment]
Thanks
