### ISSUE TITLE
Question about target column

### ISSUE THREAD

**Issue by SeibertronSS** [salesforce/OmniXAI#77]
I found some codes in TabularExplainer(line 122, 123)
```
if training_data.target_column is not None:
    self.data = self.data[:, :-1]
```
Does that mean the target column must be the last column?

**Comment by yangwenz** [comment]
After the transform, the target/label column will be the last.

**Comment by SeibertronSS** [comment]
Is transform done automatically by omnixai?

**Comment by yangwenz** [comment]
No, you need to choose the transforms as shown in the tutorial, e.g., transformer = TabularTransform().fit(tabular_data).

**Comment by SeibertronSS** [comment]
Thanks for your help !
