### ISSUE TITLE
TypeError: Explainer lime-- __init__() got an unexpected keyword argument 'handle_unknown'

### ISSUE THREAD

**Issue by costasmexis** [salesforce/OmniXAI#8]
Trying to run `https://github.com/salesforce/OmniXAI/blob/main/tutorials/tabular_regression.ipynb ` and I get:

`TypeError: Explainer shap -- __init__() got an unexpected keyword argument 'handle_unknown'` 

in cell:

```
# Initialize a TabularExplainer
explainers = TabularExplainer(
    explainers=["lime", "shap", "sensitivity", "pdp", "ale"],
    mode="regression",
    data=train_data,
    model=rf,
    preprocess=preprocess,
    params={
        "lime": {"kernel_width": 3},
        "shap": {"nsamples": 100}
    }
)
# Generate explanations
test_instances = test_data[0:5]
local_explanations = explainers.explain(X=test_instances)
global_explanations = explainers.explain_global(
    params={"pdp": {"features": ["MedInc", "HouseAge", "AveRooms",
                                 "AveBedrms", "Population", "AveOccup",
                                 "Latitude", "Longitude"]}}
)
```

**Comment by yangwenz** [comment]
This is an issue due to python version < 3.7.5. Please try python >= 3.7.5. We will update the setup file in the next release.

**Comment by yangwenz** [comment]
Check https://github.com/salesforce/OmniXAI/issues/5 for more details.

**Comment by costasmexis** [comment]
I notice that by changing in file `\.local\lib\python3.8\site-packages\omnixai\preprocessing\encode.py ` line 90: ` self.encoder = preprocessing.OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)` to `self.encoder = preprocessing.OrdinalEncoder()`, the problem is fixed.

**Comment by yangwenz** [comment]
Thanks a lot for the debugging. The scikit-learn version needs to be >= 0.24. We will revise the setup file.
